# Generated by Django 5.2.5 on 2025-08-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cart_shipping_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
