# Generated by Django 5.2.5 on 2025-08-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_address_phone'),
        ('ecommerce', '0005_cart_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
