# Generated by Django 5.2.5 on 2025-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
    ]
