# Generated by Django 5.2.5 on 2025-08-12 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_review_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('🧡', '🧡'), ('🧡🧡', '🧡🧡'), ('🧡🧡🧡', '🧡🧡🧡'), ('🧡🧡🧡🧡', '🧡🧡🧡🧡'), ('🧡🧡🧡🧡🧡', '🧡🧡🧡🧡🧡')], default='🧡🧡🧡🧡🧡', max_length=10),
        ),
    ]
